// Generated by gencpp from file probot_msgs/IOStatus.msg
// DO NOT EDIT!


#ifndef PROBOT_MSGS_MESSAGE_IOSTATUS_H
#define PROBOT_MSGS_MESSAGE_IOSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace probot_msgs
{
template <class ContainerAllocator>
struct IOStatus_
{
  typedef IOStatus_<ContainerAllocator> Type;

  IOStatus_()
    : inputIOs()
    , outputIOs()  {
    }
  IOStatus_(const ContainerAllocator& _alloc)
    : inputIOs(_alloc)
    , outputIOs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _inputIOs_type;
  _inputIOs_type inputIOs;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _outputIOs_type;
  _outputIOs_type outputIOs;



  enum {
    IO_LOW = 0,
    IO_HIGH = 1,
  };


  typedef boost::shared_ptr< ::probot_msgs::IOStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::probot_msgs::IOStatus_<ContainerAllocator> const> ConstPtr;

}; // struct IOStatus_

typedef ::probot_msgs::IOStatus_<std::allocator<void> > IOStatus;

typedef boost::shared_ptr< ::probot_msgs::IOStatus > IOStatusPtr;
typedef boost::shared_ptr< ::probot_msgs::IOStatus const> IOStatusConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::probot_msgs::IOStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::probot_msgs::IOStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace probot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'probot_msgs': ['/home/cxw/robotic_ws/src/probot_anno/probot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::IOStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::probot_msgs::IOStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::IOStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::probot_msgs::IOStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::IOStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::probot_msgs::IOStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::probot_msgs::IOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b01f2a264a951d41a72a20bf487359e0";
  }

  static const char* value(const ::probot_msgs::IOStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb01f2a264a951d41ULL;
  static const uint64_t static_value2 = 0xa72a20bf487359e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::probot_msgs::IOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "probot_msgs/IOStatus";
  }

  static const char* value(const ::probot_msgs::IOStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::probot_msgs::IOStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] inputIOs\n\
int8[] outputIOs\n\
\n\
int8 IO_LOW = 0\n\
int8 IO_HIGH = 1\n\
";
  }

  static const char* value(const ::probot_msgs::IOStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::probot_msgs::IOStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inputIOs);
      stream.next(m.outputIOs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IOStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::probot_msgs::IOStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::probot_msgs::IOStatus_<ContainerAllocator>& v)
  {
    s << indent << "inputIOs[]" << std::endl;
    for (size_t i = 0; i < v.inputIOs.size(); ++i)
    {
      s << indent << "  inputIOs[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.inputIOs[i]);
    }
    s << indent << "outputIOs[]" << std::endl;
    for (size_t i = 0; i < v.outputIOs.size(); ++i)
    {
      s << indent << "  outputIOs[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.outputIOs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROBOT_MSGS_MESSAGE_IOSTATUS_H
